HTTP_ACCESS_FILE_HANDLER_NAME = "http_access_file_handler"
HTTP_ERR_FILE_HANDLER_NAME = "http_err_file_handler"
HTTP_ACCESS_JSON_HANDLER_NAME = "http_access_json_handler"
HTTP_ERR_JSON_HANDLER_NAME = "http_err_json_handler"

HTTP_HANDLER_NAMES = [
    HTTP_ACCESS_FILE_HANDLER_NAME,
    HTTP_ERR_FILE_HANDLER_NAME,
    HTTP_ACCESS_JSON_HANDLER_NAME,
    HTTP_ERR_JSON_HANDLER_NAME,
]


__all__ = [
    "HTTP_ACCESS_FILE_HANDLER_NAME",
    "HTTP_ERR_FILE_HANDLER_NAME",
    "HTTP_ACCESS_JSON_HANDLER_NAME",
    "HTTP_ERR_JSON_HANDLER_NAME",
    "HTTP_HANDLER_NAMES",
]
